version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - NEO4J_URI=bolt://neo4j:7687
    depends_on:
      - neo4j
    networks:
      - app-network

  neo4j:
    image: neo4j:4.4
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/your-password-here
    networks:
      - app-network

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  app-network:
    driver: bridge 